#title = "Http Toml"

[http]
host = "0.0.0.0:8082"

[redis]
host = "192.168.199.159:6379"
password = ""
db = 0
proxy2layer_queue_name = "sec_queue"          ### 接入层->逻辑层
layer2proxy_queue_name = "recv_queue"         ### 逻辑层->接入层
id_black_list_hash = "id_black_list_hash"     ### 用户黑名单Hash表
ip_black_list_hash = "ip_black_list_hash"     ### IP黑名单Hash表
id_black_list_queue = "id_black_list_queue"   ### 用户黑名单队列
ip_black_list_queue = "ip_black_list_queue"   ### IP黑名单队列

[etcd]
host = "192.168.199.159:2379"
product_key = "sec_kill_product"
black_list_key = "sec_kill_backlist"

[service]
#频率控制阈值
ip_sec_access_limit = 50
user_sec_access_limit = 1
ip_min_access_limit = 500
user_min_access_limit = 10
#cookie 秘钥
cookie_secretkey = "WK5wJOiuYaXRUlPsxo3LZEbpCNSyvm8T"
#白名单
refer_whitelist= "127.0.0.1"
#goroutine数量控制
write_proxy2layer_goroutine_num = 16
read_proxy2layer_goroutine_num = 16